### ISSUE TITLE
unable to build from uncommitted changes

### ISSUE THREAD

**Issue by zjosua** [glutanimate/anki-addon-builder#3]
Is there a specific reason why building from uncommitted files is not possible?

Imo it is very counter-intuitive to be forced to commit my untested changes to make testing even possible.

**Comment by glutanimate** [comment]
(Sorry about the delayed response). It's a technical limitation rather than a conscious design decision. Building from uncommitted files would definitely be a lot more convenient. Unfortunately the code is so tightly bound to be working with git archives (e.g. to designate files to be included or ignored via `.gitattributes` and `.gitignore`) that I'm not sure if there is an easy way to implement this. However, if anyone finds a workable solution I'd be more than happy to merge it!
